<?php

/**
 * @file 
 */

/**
 * @defgroup process_image  
 * @ingroup imagess
 * @{
 *
 * The Process Images module is using C++ DLL to get the properties of the uploaded images
 * @link http:// . @endlink
 */

/**
 * Implements hook_menu().
 *
 * Here we set up the URLs (menu entries). Note that most of the menu items
 * have page callbacks and page arguments set, with
 * page arguments set to be functions in external files.
 */
function process_image_menu() {
  $items = array();
  $items['images/process_image'] = array(
    'title' => 'Process Image',
    'page callback' => 'process_image_intro',
    'access callback' => TRUE,
    'expanded' => TRUE,
  ); 

  $items['images/process_image/upload_image'] = array(
    'title' => 'Upload Image and show its properties',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('process_image_demo_form'),
    'access callback' => TRUE,
    'file' => 'process_image.inc',
    'weight' => 1,
  );
      
  return $items;
}

/**
 * Page callback for our general info page.
 */
function process_image_intro() {
  $markup = t('The form example module provides a tutorial, extensible multistep example, an element example, and a #states example');
  return array('#markup' => $markup);
}

/**
 * Implements hook_help().
 */
function process_image_help($path, $arg) {
  switch ($path) { 
    case 'examples/process_image/upload_image':
      $help = t('Upload the image and show its properties.');
      break;
  }
  if (!empty($help)) {
    return '<p>' . $help . '</p>';
  }
}


/**
 * Implements hook_element_info().
 * 
 * This just returns _process_image_info().
 */
function process_image_info() {
  require_once 'process_image.inc';
  return _process_image_info();
}

/**
 * Implements hook_theme().
 *
 * This returns _process_image_element_theme().
 */
function process_image_theme($existing, $type, $theme, $path) {
  require_once 'process_image.inc';
  return _process_image_theme($existing, $type, $theme, $path);
}
/**
 * @} End of "defgroup process_image".
 */
